STUDY:
  name: study-name
  description: ""
  version: 1.0

PARAMETERS:
    param-name1:
      value: []
      mode: linear
    param-name2:
      value: []
      mode: combinatoric

FILES:
    - path: path1
      files:
        - filename1
    - path: path2
      files:
        - filename1
        - filename2
